---
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: bond0.777
spec:
  desiredState:
    interfaces:
      - name: bond0.777
        type: vlan
        state: up
        vlan:
          base-iface: bond0
          id: 777
        ipv4:
          enabled: false
          dhcp: false
        ipv6:
          enabled: false
          dhcp: false
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: vlan-777-bond0
  namespace: engineering-vms
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "vlan-777-bond0",
    "type": "cnv-bridge",
    "master": "bond0.777",
    "macspoofchk": false,
    "preserveDefaultVlan": false,
    "ipam": {
      "type": "whereabouts",
      "range": "192.168.99.0/24"
    }
  }'
