---
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: bond0.777
spec:
  desiredState:
    interfaces:
      - name: bond0.777
        type: vlan
        state: up
        vlan:
          base-iface: bond0
          id: 777
        ipv4:
          enabled: false
          dhcp: false
        ipv6:
          enabled: false
          dhcp: false
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: vlan-777-bond0
  namespace: aardvark
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "vlan-777-bond0",
    "type": "cnv-bridge",
    "bridge": "bond0.777",
    "macspoofchk": false,
    "preserveDefaultVlan": true,
    "ipam": {
      "type": "host-local",
      "subnet": "192.168.1.0/24",
      "rangeStart": "192.168.1.100",
      "rangeEnd": "192.168.1.200",
      "routes": [
        { "dst": "0.0.0.0/0" }
      ],
      "gateway": "192.168.1.1"
    }
  }'
