---
apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: engineering
users:
  - therevoman
  - daniel
  - thomasphall
---
kind: Project
apiVersion: project.openshift.io/v1
metadata:
  name: engineering-vms
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: engineering-vms-user
  namespace: engineering-vms
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: engineering
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: engineering-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: engineering-vms-admin
  namespace: engineering-vms
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: engineering-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vm-templates-engineering-users
  namespace: engineering-vms
rules:
  - verbs:
      - get
      - watch
      - list
      - create
    apiGroups:
      - processedtemplates.template.openshift.io
      - template.openshift.io
    resources:
      - processedtemplates
  - verbs:
      - get
      - watch
      - list
    apiGroups:
      - k8s.cni.cncf.io
    resources:
      - network-attachment-definitions
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-binding-engineering-group-vm-templates
  namespace: engineering-vms
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: engineering
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: engineering-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vm-templates-engineering-users
