apiVersion: v1
kind: Pod
metadata:
  name: ubi9
  labels:
    app: ubi9
  namespace: multi-cloud
spec:
  containers:
    - name: ubi9
      image: 'registry.access.redhat.com/ubi9/ubi'
      stdin: true
      tty: true

